### ISSUE TITLE
連續翻譯20 次問題

### ISSUE THREAD

**Issue by Yucie** [ZCY01/BaiduTranslate#3]
你好, 我想問一下
因為我短時間連續使用20次以後, 便會出現401 不能使用問題
要等分數鐘才能夠使用
請問有什麼方法可破解401 的問題
謝謝

**Comment by ZCY01** [comment]
我觉得可能是百度服务器那边做了限流/反爬虫，短时间频繁查询直接返回401。
我试了一下，一秒一次查询没有什么问题。有待研究。

**Comment by Yucie** [comment]
因為自己破不了那401 的問題, 所以我自己用了很笨而且很慢的方法
selenium -> 呼叫網頁 -> 再抓取翻譯後的數據. 
這樣的話沒有401 問題, 但是這樣需要10數秒才能翻一句.
希望大大可以幫忙破解401 的問題
謝謝

**Comment by seozed** [comment]
1秒一次就行了，用不着上selenium
